name: Terraform infraestructura Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy_and_destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t infraestructura .

    - name: Build Docker image
      run:  docker run --rm -v $(pwd):/workspace -w /workspace terraform-project init 

    - name: Run Terraform apply
      run: docker run --rm -v $(pwd):/workspace -w /workspace infraestructura apply -auto-approve

    - name: Run Terraform destroy
      run: docker run --rm -v $(pwd):/workspace -w /workspace infraestructura destroy -auto-approve